### ISSUE TITLE
Wrong applicationID

### ISSUE THREAD

**Issue by Celtiore** [bizz84/firebase_user_avatar_flutter#1]
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:processDebugGoogleServices'.            
> No matching client found for package name 'com.example.firebase_user_avatar_flutter'

You need replace in android/app/build.gradle : 
line 41 : 

        applicationId "com.example.firebase_user_avatar_flutter"
by
        applicationId "com.codingwithflutter.firebase_user_avatar_flutter"

**Comment by bizz84** [comment]
Thanks for reporting this.

It's actually the other way around. Both the `build.gradle` and `AndroidManifest.xml` use `com.example.firebase_user_avatar_flutter` as the package name.

I have updated this on the README.

**Comment by Celtiore** [comment]
Thanks you
